"""add_self_heal

Revision ID: 2645b64912c2
Revises: e40e0f79afe5
Create Date: 2026-05-02 06:29:18.075969
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '2645b64912c2'
down_revision: Union[str, None] = 'e40e0f79afe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_quality', sa.Float(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index('ix_conv_health_conversation', 'conversation_health', ['conversation_id'], unique=False)
    op.add_column('dual_execution_records', sa.Column('is_contrast_pair', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('dual_execution_records', sa.Column('contrast_improved', sa.Text(), nullable=True))
    op.add_column('routing_decisions', sa.Column('self_healed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('routing_decisions', sa.Column('heal_score_before', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routing_decisions', 'heal_score_before')
    op.drop_column('routing_decisions', 'self_healed')
    op.drop_column('dual_execution_records', 'contrast_improved')
    op.drop_column('dual_execution_records', 'is_contrast_pair')
    op.drop_index('ix_conv_health_conversation', table_name='conversation_health')
    op.drop_table('conversation_health')
    # ### end Alembic commands ###
