"""add_uploaded_files_table

Revision ID: 6b96a4eb723a
Revises: 84542bc110a7
Create Date: 2026-05-06 17:34:51.052450
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6b96a4eb723a'
down_revision: Union[str, None] = '84542bc110a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_created', 'uploaded_files', ['created_at'], unique=False)
    op.create_index('ix_uploaded_files_purpose', 'uploaded_files', ['purpose'], unique=False)
    op.create_index('ix_uploaded_files_workspace', 'uploaded_files', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uploaded_files_workspace', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_purpose', table_name='uploaded_files')
    op.drop_index('ix_uploaded_files_created', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
