"""add_provisioning_tables

Revision ID: 84542bc110a7
Revises: c5b82e1d4a09
Create Date: 2026-05-06 02:35:10.432535
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '84542bc110a7'
down_revision: Union[str, None] = 'c5b82e1d4a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlas_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('tenant_name', sa.String(length=256), nullable=False),
    sa.Column('tenant_owner_email', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('default_model', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requests_total', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('active','disabled','revoked')", name='chk_atlas_key_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_atlas_api_keys_key_hash', 'atlas_api_keys', ['key_hash'], unique=False)
    op.create_index('ix_atlas_api_keys_tenant_id', 'atlas_api_keys', ['tenant_id'], unique=False)
    op.create_table('provisioning_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=True),
    sa.Column('alpheric_key_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('safe_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prov_audit_created_at', 'provisioning_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_prov_audit_tenant_id', 'provisioning_audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prov_audit_tenant_id', table_name='provisioning_audit_logs')
    op.drop_index('ix_prov_audit_created_at', table_name='provisioning_audit_logs')
    op.drop_table('provisioning_audit_logs')
    op.drop_index('ix_atlas_api_keys_tenant_id', table_name='atlas_api_keys')
    op.drop_index('ix_atlas_api_keys_key_hash', table_name='atlas_api_keys')
    op.drop_table('atlas_api_keys')
    # ### end Alembic commands ###
