"""add_vector_store_tables

Revision ID: 8dc3de7dce71
Revises: 6b96a4eb723a
Create Date: 2026-05-06 17:54:40.579074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers
revision: str = '8dc3de7dce71'
down_revision: Union[str, None] = '6b96a4eb723a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_stores',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vector_stores_workspace', 'vector_stores', ['workspace_id'], unique=False)
    op.create_table('vector_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['vector_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vector_chunks_file', 'vector_chunks', ['file_id'], unique=False)
    op.create_index('ix_vector_chunks_store', 'vector_chunks', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vector_chunks_store', table_name='vector_chunks')
    op.drop_index('ix_vector_chunks_file', table_name='vector_chunks')
    op.drop_table('vector_chunks')
    op.drop_index('ix_vector_stores_workspace', table_name='vector_stores')
    op.drop_table('vector_stores')
    # ### end Alembic commands ###
