"""add_batches_table

Revision ID: e904f11f09fe
Revises: 8dc3de7dce71
Create Date: 2026-05-06 18:05:17.853984
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'e904f11f09fe'
down_revision: Union[str, None] = '8dc3de7dce71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('input_file_id', sa.String(length=64), nullable=False),
    sa.Column('output_file_id', sa.String(length=64), nullable=True),
    sa.Column('error_file_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('completion_window', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('completed_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workspace_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('in_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batches_created', 'batches', ['created_at'], unique=False)
    op.create_index('ix_batches_status', 'batches', ['status'], unique=False)
    op.create_index('ix_batches_workspace', 'batches', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_batches_workspace', table_name='batches')
    op.drop_index('ix_batches_status', table_name='batches')
    op.drop_index('ix_batches_created', table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
