"""initial_schema

Revision ID: f88eb00604a7
Revises: 
Create Date: 2026-04-24 21:31:21.772306
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'f88eb00604a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('avg_quality', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('avg_cost_usd', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', 'provider', 'model', 'period')
    )
    op.create_table('provider_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_month_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_accounts_provider', 'provider_accounts', ['provider'], unique=False)
    op.create_table('task_type_readiness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=16), nullable=False),
    sa.Column('claude_sample_count', sa.Integer(), nullable=False),
    sa.Column('training_threshold', sa.Integer(), nullable=False),
    sa.Column('local_avg_quality', sa.Float(), nullable=False),
    sa.Column('quality_gate_score', sa.Float(), nullable=False),
    sa.Column('lm_eval_score', sa.Float(), nullable=True),
    sa.Column('local_handoff_pct', sa.Float(), nullable=False),
    sa.Column('max_local_pct', sa.Float(), nullable=False),
    sa.Column('best_local_model', sa.String(length=128), nullable=True),
    sa.Column('last_training_run_id', sa.String(length=36), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canary_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_regression_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('argilla_review_status', sa.String(length=32), nullable=True),
    sa.Column('argilla_batch_id', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle_state IN ('learning','training','evaluating','canary','graduated','retired')", name='chk_lifecycle_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type')
    )
    op.create_index('ix_task_readiness_task', 'task_type_readiness', ['task_type'], unique=False)
    op.create_table('usage_hourly_rollups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('equivalent_external_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash', 'provider', 'model', 'is_local', 'hour')
    )
    op.create_index('ix_usage_hourly_hour', 'usage_hourly_rollups', ['hour'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computer_use_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_workspaces_slug', 'workspaces', ['slug'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('atlas_model', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('app_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_workspace', 'applications', ['workspace_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.String(length=256), nullable=True),
    sa.Column('reviewed_by', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='chk_approval_status'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_entity', 'approval_requests', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=256), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type'], unique=False)
    op.create_index('ix_audit_events_workspace', 'audit_events', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('dual_execution_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('request_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claude_model', sa.String(length=128), nullable=False),
    sa.Column('claude_response', sa.Text(), nullable=False),
    sa.Column('claude_latency_ms', sa.Integer(), nullable=False),
    sa.Column('claude_prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('claude_completion_tokens', sa.Integer(), nullable=False),
    sa.Column('local_model', sa.String(length=128), nullable=True),
    sa.Column('local_response', sa.Text(), nullable=True),
    sa.Column('local_latency_ms', sa.Integer(), nullable=True),
    sa.Column('local_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('local_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dual_exec_created', 'dual_execution_records', ['created_at'], unique=False)
    op.create_index('ix_dual_exec_task_type', 'dual_execution_records', ['task_type'], unique=False)
    op.create_table('notebooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('kernel', sa.String(length=64), nullable=False),
    sa.Column('atlas_model', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notebooks_workspace', 'notebooks', ['workspace_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('atlas_model', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_workspace', 'teams', ['workspace_id'], unique=False)
    op.create_table('training_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('base_model', sa.String(length=256), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('ollama_model', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')"),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('equivalent_external_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['provider_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_records_api_key_created', 'usage_records', ['api_key_hash', 'created_at'], unique=False)
    op.create_index('ix_usage_records_created', 'usage_records', ['created_at'], unique=False)
    op.create_index('ix_usage_records_provider_model', 'usage_records', ['provider', 'model'], unique=False)
    op.create_table('workspace_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('monthly_limit_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_month_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('alert_threshold_pct', sa.Float(), nullable=False),
    sa.Column('budget_month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_index('ix_workspace_budgets_workspace', 'workspace_budgets', ['workspace_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('atlas_model', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name')
    )
    op.create_index('ix_agents_app', 'agents', ['app_id'], unique=False)
    op.create_index('ix_agents_workspace', 'agents', ['workspace_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name')
    )
    op.create_index('ix_channels_team', 'channels', ['team_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('system', 'user', 'assistant', 'tool')"),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence')
    )
    op.create_index('ix_messages_conversation_seq', 'messages', ['conversation_id', 'sequence'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('base_model', sa.String(length=256), nullable=False),
    sa.Column('adapter_path', sa.Text(), nullable=True),
    sa.Column('training_run_id', sa.UUID(), nullable=True),
    sa.Column('eval_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','staging','active','retired')", name='chk_model_version_status'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_versions_status', 'model_versions', ['status'], unique=False)
    op.create_index('ix_model_versions_task', 'model_versions', ['task_type'], unique=False)
    op.create_table('notebook_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('cell_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('execution_state', sa.String(length=16), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("cell_type IN ('code','markdown','ai')", name='chk_cell_type'),
    sa.CheckConstraint("execution_state IN ('idle','running','completed','error')", name='chk_cell_exec_state'),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notebook_cells_notebook', 'notebook_cells', ['notebook_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_executions_agent', 'agent_executions', ['agent_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=True),
    sa.Column('to_agent_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','processing','completed','failed')", name='chk_amsg_status'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_messages_status', 'agent_messages', ['status'], unique=False)
    op.create_index('ix_agent_messages_to', 'agent_messages', ['to_agent_id'], unique=False)
    op.create_table('channel_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin','member','viewer')", name='chk_member_role'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id')
    )
    op.create_index('ix_channel_members_channel', 'channel_members', ['channel_id'], unique=False)
    op.create_index('ix_channel_members_user', 'channel_members', ['user_id'], unique=False)
    op.create_table('computer_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('screenshot_count', sa.Integer(), nullable=False),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','completed','failed','terminated')", name='chk_computer_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_computer_sessions_agent', 'computer_sessions', ['agent_id'], unique=False)
    op.create_index('ix_computer_sessions_workspace', 'computer_sessions', ['workspace_id'], unique=False)
    op.create_table('model_deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('target_server', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','deploying','active','failed','removed')", name='chk_deployment_status'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_deployments_version', 'model_deployments', ['model_version_id'], unique=False)
    op.create_table('quality_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('evaluator', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("signal_type IN ('thumbs', 'score', 'auto_eval', 'comparison')"),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_signals_message', 'quality_signals', ['message_id'], unique=False)
    op.create_table('routing_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fallback_from', sa.UUID(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['provider_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fallback_from'], ['routing_decisions.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routing_decisions_created', 'routing_decisions', ['created_at'], unique=False)
    op.create_index('ix_routing_decisions_task_type', 'routing_decisions', ['task_type'], unique=False)
    op.create_table('task_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('root_task', sa.Text(), nullable=False),
    sa.Column('decomposed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('executor_agent_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('planning','executing','completed','failed','cancelled')", name='chk_plan_status'),
    sa.ForeignKeyConstraint(['executor_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_plans_status', 'task_plans', ['status'], unique=False)
    op.create_index('ix_task_plans_workspace', 'task_plans', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_plans_workspace', table_name='task_plans')
    op.drop_index('ix_task_plans_status', table_name='task_plans')
    op.drop_table('task_plans')
    op.drop_index('ix_routing_decisions_task_type', table_name='routing_decisions')
    op.drop_index('ix_routing_decisions_created', table_name='routing_decisions')
    op.drop_table('routing_decisions')
    op.drop_index('ix_quality_signals_message', table_name='quality_signals')
    op.drop_table('quality_signals')
    op.drop_index('ix_model_deployments_version', table_name='model_deployments')
    op.drop_table('model_deployments')
    op.drop_index('ix_computer_sessions_workspace', table_name='computer_sessions')
    op.drop_index('ix_computer_sessions_agent', table_name='computer_sessions')
    op.drop_table('computer_sessions')
    op.drop_index('ix_channel_members_user', table_name='channel_members')
    op.drop_index('ix_channel_members_channel', table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index('ix_agent_messages_to', table_name='agent_messages')
    op.drop_index('ix_agent_messages_status', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_agent_executions_agent', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index('ix_notebook_cells_notebook', table_name='notebook_cells')
    op.drop_table('notebook_cells')
    op.drop_index('ix_model_versions_task', table_name='model_versions')
    op.drop_index('ix_model_versions_status', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('ix_messages_conversation_seq', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_channels_team', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_agents_workspace', table_name='agents')
    op.drop_index('ix_agents_app', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_workspace_budgets_workspace', table_name='workspace_budgets')
    op.drop_table('workspace_budgets')
    op.drop_index('ix_usage_records_provider_model', table_name='usage_records')
    op.drop_index('ix_usage_records_created', table_name='usage_records')
    op.drop_index('ix_usage_records_api_key_created', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('training_runs')
    op.drop_index('ix_teams_workspace', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_notebooks_workspace', table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index('ix_dual_exec_task_type', table_name='dual_execution_records')
    op.drop_index('ix_dual_exec_created', table_name='dual_execution_records')
    op.drop_table('dual_execution_records')
    op.drop_table('conversations')
    op.drop_index('ix_audit_events_workspace', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests')
    op.drop_index('ix_approval_requests_entity', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_applications_workspace', table_name='applications')
    op.drop_table('applications')
    op.drop_table('api_keys')
    op.drop_index('ix_workspaces_slug', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_usage_hourly_hour', table_name='usage_hourly_rollups')
    op.drop_table('usage_hourly_rollups')
    op.drop_index('ix_task_readiness_task', table_name='task_type_readiness')
    op.drop_table('task_type_readiness')
    op.drop_index('ix_provider_accounts_provider', table_name='provider_accounts')
    op.drop_table('provider_accounts')
    op.drop_table('model_performance')
    # ### end Alembic commands ###
