import fs from "fs";
import path from "path";
import { WorkspaceInfo } from "./workspace.js";
import { DEFAULT_PERMISSIONS, savePermissions } from "./permissions.js";

export interface InitResult {
  created: string[]; // paths created
  skipped: string[]; // paths that already existed
  atlasMd: string; // the generated ATLAS.md content
}

const MEMORY_TEMPLATE = `# Project Memory

> This file is read by Atlas at the start of each session.
> Add notes, decisions, and context here.

## Key Decisions

## Known Issues

## Useful Context
`;

function ensureDir(dirPath: string, created: string[], skipped: string[]): void {
  if (fs.existsSync(dirPath)) {
    skipped.push(dirPath);
  } else {
    fs.mkdirSync(dirPath, { recursive: true });
    created.push(dirPath);
  }
}

function writeIfNotExists(
  filePath: string,
  content: string,
  created: string[],
  skipped: string[]
): void {
  if (fs.existsSync(filePath)) {
    skipped.push(filePath);
  } else {
    fs.writeFileSync(filePath, content, "utf-8");
    created.push(filePath);
  }
}

function getProjectName(workspaceRoot: string): string {
  const pkgPath = path.join(workspaceRoot, "package.json");
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as { name?: string };
      if (pkg.name) return pkg.name;
    } catch {
      // ignore
    }
  }
  return path.basename(workspaceRoot);
}

function generateAtlasMd(workspaceRoot: string, info: WorkspaceInfo): string {
  const projectName = getProjectName(workspaceRoot);

  const techStack: string[] = [];
  if (info.framework) techStack.push(info.framework);
  if (info.packageManager) techStack.push(`Package manager: ${info.packageManager}`);

  const detectedFilesList =
    info.detectedFiles.length > 0
      ? info.detectedFiles.map((f) => `- \`${f}\``).join("\n")
      : "- (none detected)";

  const techStackSection =
    techStack.length > 0
      ? techStack.map((t) => `- ${t}`).join("\n")
      : "- (fill in your tech stack here)";

  return `# ${projectName}

> Auto-generated by \`atlas init\`. Fill in the sections marked with TODO.

## Overview

TODO: Describe what this project does in 2-3 sentences.

## Tech Stack

${techStackSection}

## Detected Files

${detectedFilesList}

## Commands

\`\`\`bash
# Development
TODO: add dev command (e.g. npm run dev)

# Build
TODO: add build command (e.g. npm run build)

# Test
TODO: add test command (e.g. npm test)
\`\`\`

## Architecture Notes

TODO: Describe the high-level architecture, key modules, and how they connect.

## Important Notes

TODO: Add any important context Atlas should know when working on this project.
- Known constraints or limitations
- Coding conventions specific to this project
- Areas to be careful about
`;
}

export async function runAtlasInit(
  workspaceRoot: string,
  info: WorkspaceInfo
): Promise<InitResult> {
  const created: string[] = [];
  const skipped: string[] = [];

  // 1. Create .atlas/ directory
  const atlasDir = path.join(workspaceRoot, ".atlas");
  ensureDir(atlasDir, created, skipped);

  // 2. Create .atlas/settings.json with DEFAULT_PERMISSIONS
  const settingsPath = path.join(atlasDir, "settings.json");
  if (fs.existsSync(settingsPath)) {
    skipped.push(settingsPath);
  } else {
    savePermissions(atlasDir, DEFAULT_PERMISSIONS);
    created.push(settingsPath);
  }

  // 3. Create .atlas/memory.md
  const memoryPath = path.join(atlasDir, "memory.md");
  writeIfNotExists(memoryPath, MEMORY_TEMPLATE, created, skipped);

  // 4. Create .atlas/commands/ directory
  const commandsDir = path.join(atlasDir, "commands");
  ensureDir(commandsDir, created, skipped);

  // 5. Create .atlas/logs/ directory
  const logsDir = path.join(atlasDir, "logs");
  ensureDir(logsDir, created, skipped);

  // 6. Generate ATLAS.md in workspace root
  const atlasMd = generateAtlasMd(workspaceRoot, info);
  const atlasMdPath = path.join(workspaceRoot, "ATLAS.md");
  writeIfNotExists(atlasMdPath, atlasMd, created, skipped);

  return { created, skipped, atlasMd };
}
